spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disaster_renewer?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dudgks56!!

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
logging.level:
  org.hibernate.SQL: debug

chatgpt:
  api-key: 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


my:
  api:
    key:
      hostpital: A8m%2BLiXkYxIQHFPAUy7wLpqhw6YVD1oJnSsMAviqFWEVArg2KDkCBkPRdjyuoPMFKGp0Rl8DXCoa4SqWo5IH4g%3D%3D
      message: 0B8T785T3DZWP60N
      police: A8m%2BLiXkYxIQHFPAUy7wLpqhw6YVD1oJnSsMAviqFWEVArg2KDkCBkPRdjyuoPMFKGp0Rl8DXCoa4SqWo5IH4g%3D%3D